version: '3.9'

services:

  housekeeper-frontend:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: ${CONTAINER_REGISTRY}/housekeeper-frontend:${TAG}
    container_name: housekeeper-frontend
    restart: always
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8141:80"
    environment:
      - BUILD_NUMBER=${TAG}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.housekpr-ui.rule=Host(`housekpr.ru`)"
    networks:
      - printdown-network

networks:
  printdown-network:
    external: true