services:

  housekeeper-frontend:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: lobanovsky/housekeeper-frontend:${TAG}
    container_name: housekeeper-frontend
    restart: always
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "80"
    environment:
      - BUILD_NUMBER=${TAG}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.housekpr.rule=Host(`housekpr.ru`)"
      - "traefik.http.routers.housekpr.entrypoints=https"
      - "traefik.http.routers.housekpr.tls=true"
      - "traefik.http.routers.housekpr.tls.certresolver=letsEncrypt"
    networks:
      - housekpr-network

networks:
  housekpr-network:
    external: true